[build]
target = "x86_64-unknown-none"

rustflags = [
    "-Clink-arg=-Tsrc/linker.ld",
    # "-Crelocation-model=static",
    # "-Zbuild-std with panic=\"abort\"",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
