[build]
target = "x86_64-unknown-none"
target-dir = "./target"

rustflags = ["-C", "link-arg=-TNcore/linker.ld"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]