[package]
name = "monolithic-objects"
version = "0.1.0"
edition = "2024"

[dependencies]
hybrid-objects = {path = "../hybrid-objects"}
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
spin = "0.10.0"
trapframe = {path = "../crates/trapframe-rs"}
executor = {path = "../executor"}
rcore-fs = {git = "https://github.com/rcore-os/rcore-fs"}
log = "0.4.27"
xmas-elf = "0.10.0"
x86_64 = "0.15.2"
bitflags = "2.9.1"
hal ={ path = "../hal"}
user-syscall = { path = "../user-components/user-syscall"}
rcore-fs-sfs = { git = "https://github.com/rcore-os/rcore-fs" }
rcore-fs-mountfs = { git = "https://github.com/rcore-os/rcore-fs" }
rcore-fs-devfs = { git = "https://github.com/rcore-os/rcore-fs" }
num = { version = "0.4", default-features = false }
num-derive = { version = "0.4", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
numeric-enum-macro = "0.2.0"
