[package]
name = "loader"
version = "0.1.0"
edition = "2024"

[dependencies]
trapframe = { path = "../crates/trapframe-rs" }
executor = {path = "../executor"}
hal = {path = "../hal"}
log = "0.4.27"
cfg-if = "1.0"
hybrid-syscalls = { path = "../hybrid-syscalls", optional = true }
hybrid-objects = { path = "../hybrid-objects", optional = true }
monolithic-objects = { path = "../monolithic-objects", optional = true }
monolithic-syscalls = { path = "../monolithic-syscalls", optional = true }
bootloader_api = "0.11"
num-derive = { version = "0.4", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
x86_64 = "0.15.2"

[features]
# default = ["hybrid"]
default = []
# default = ["monolithic"]
monolithic = ["monolithic-objects", "monolithic-syscalls"]
hybrid = ["hybrid-objects", "hybrid-syscalls"]
