[package]
name = "user_lib"
version = "0.1.0"
authors = [
    "Yifan Wu <shinbokuow@163.com>",
    "Yuekai Jia <equation618@gmail.com>",
]
edition = "2021"

[dependencies]
bitflags = "1"
buddy_system_allocator = "*"
